import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Github Repositories Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-2 bg-gray-100">
        <div className="h-screen overflow-auto bg-white p-4 rounded m-auto sm:w-3/4">
          {children}
        </div>
      </body>
    </html>
  );
}
